version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nuestable-postgres
    environment:
      POSTGRES_USER: nuestable
      POSTGRES_PASSWORD: nuestable
      POSTGRES_DB: nuestable
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nuestable-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
